# Generated by Django 3.1.7 on 2021-04-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('apelidp', models.CharField(blank=True, max_length=30)),
                ('ultimo_nome', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('proveniencia', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Suplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('apelidp', models.CharField(blank=True, max_length=30)),
                ('ultimo_nome', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('data_contratacao', models.DateField(auto_now=True)),
                ('endereco', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=30)),
                ('apelidp', models.CharField(blank=True, max_length=30)),
                ('ultimo_nome', models.CharField(max_length=30)),
                ('data_nascimento', models.DateField()),
                ('data_contratacao', models.DateField(auto_now=True)),
                ('endereco', models.CharField(max_length=100)),
                ('funcao', models.CharField(max_length=20)),
                ('tempo_contrato', models.IntegerField()),
                ('documento_identificacao', models.CharField(max_length=15)),
                ('nivel_academico', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konjevi.user')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konjevi.product')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atendente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konjevi.user')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konjevi.room')),
            ],
        ),
    ]
